language: node_js
node_js:
  - 5.1.0
before_scripts:
  - npm install -g mocha
  - npm install git
  - npm install image-size --save

branches:
  only:
  - master
  
env:
    - commit = $TRAVIS_COMMIT_RANGE

after_success: |
  if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then
    git remote add public https://jrebagliatti:$GITHUB_API_KEY@github.com/jrebagliatti/test-pages-lfs-public
    git push public master
  fi